version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "1000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
  web1:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./web1/index.html:/usr/local/apache2/htdocs/index.html
  web2:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./web2/index.html:/usr/share/nginx/html/index.html
